### ISSUE TITLE
JentisTrackService fails when trying to submit an ArrayLists as part of an object in version 1.0.1

### ISSUE THREAD

**Issue by gewinter** [JENTISDev/jentis-android-sdk#4]
Using version 1.0.1 of the android sdk, it crashes when trying to submit a complex object containing an array of data.
Data tried to submit:
```json
{
  "track": "pageview", 
  "pagetitle": "Tracking Screen",
  "virtualPagePath": "MainScreen/TrackingScreen",
  "testArray": {
    "property1": ["value1", "value2"],
    "property2": "value2"
  }
}
```

Stacktrace:
```
E/AndroidRuntime( 8899): java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
E/AndroidRuntime( 8899): 	at com.jentis.tracking.sdk.JentisUtils.hashMapToJsonObjectString(JentisUtils.java:119)
E/AndroidRuntime( 8899): 	at com.jentis.tracking.sdk.JentisTrackService.submitPush(JentisTrackService.java:306)
E/AndroidRuntime( 8899): 	at com.jentis.tracking.sdk.JentisTrackService.access$500(JentisTrackService.java:25)
E/AndroidRuntime( 8899): 	at com.jentis.tracking.sdk.JentisTrackService$1.run(JentisTrackService.java:211)
E/AndroidRuntime( 8899): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/AndroidRuntime( 8899): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime( 8899): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime( 8899): 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by MichaelPirker** [comment]
The array lists (product lists) were only included in the latest version of the repository (main-productlist - default). The Maven library 1.0.1 is build with an older SW version that does not contain product lists.  Please use the latest code for testing.
